Bird.create(scientific_name: "Empidonax virescens", common_name: "Acadian Flycatcher", description: "Captures insects primarily by snatching them from leaves, especially from the undersides. Also hovers to glean insects and catches some in flight. Occasionally forages on ground.", size: "small", primary_color: "gray", secondary_color: "yellow", chest_color: "gray", distinct_pattern: ["eyerings", "wingbars"], habitat: "forest", nesting: "tree", call_description: "squeak", img: "http://www.animalspot.net/wp-content/uploads/2017/03/Acadian-Flycatcher-Images.jpg", region: ["southeast", "northeast", "middle"])

Bird.create(scientific_name: "Corvus brachyrhynchos", common_name: "American Crow", description: "American Crows are very social, sometimes forming flocks in the thousands. Inquisitive and sometimes mischievous, crows are good learners and problem-solvers, often raiding garbage cans and picking over discarded food containers. They're also aggressive and often chase away larger birds including hawks, owls and herons.", size: "large", primary_color: "black", secondary_color: "black", chest_color: "black", distinct_pattern: ["all one color"], habitat: "woodland", nesting: "tree", call_description: "caw", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/american_crow_8.jpg", region: ["southeast", "northeast", "middle", "northwest", "southwest", "middle"])

Bird.create(scientific_name: "Spinus tristis", common_name: "American Goldfinch", description: "These are active and acrobatic little finches that cling to weeds and seed socks, and sometimes mill about in large numbers at feeders or on the ground beneath them. Goldfinches fly with a bouncy, undulating pattern and often call in flight, drawing attention to themselves.", size: "small", primary_color: "yellow", secondary_color: "black", chest_color: "yellow", distinct_pattern: ["black forehead"], habitat: "woodland", nesting: "shrub", call_description: "squeak", img: "http://animalia-life.club/data_images/american-goldfinch/american-goldfinch1.jpg", region: ["northeast", "northwest", "middle", "southeast"])

Bird.create(scientific_name: "Setophaga ruticilla", common_name: "American Redstart", description: "American Redstarts are incredibly active insectivores that seem never to stand still. They rapidly spread their cocked tails, exposing the orange or yellow in a quick flash, which often startles insect prey into flushing, whereupon the redstart darts after it, attempting to catch it in the air.", size: "medium", primary_color: "black", secondary_color: "orange", chest_color: "black", distinct_pattern: ["colored streaks"], habitat: "forest", nesting: "shrub", call_description: "song-like", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/AmericanRedstart-Vyn-100515-0147.jpg", region: ["northeast", "northwest", "southeast", "southwest", "midwest", "middle"])

Bird.create(scientific_name: "Turdus migratorius", common_name: "American Robin", description: "American Robins are industrious and authoritarian birds that bound across lawns or stand erect, beak tilted upward, to survey their environs. When alighting they habitually flick their tails downward several times. In fall and winter they form large flocks and gather in trees to roost or eat berries.", size: "large", primary_color: "gray-brown", secondary_color: "orange", chest_color: "orange", distinct_pattern: ["colored streaks"], habitat: "woodland", nesting: "tree", call_description: "squeak", img: "https://s-media-cache-ak0.pinimg.com/originals/4e/13/6f/4e136fa8c750f138135773792dc21dbd.jpg", region: ["northeast", "northwest", "southeast", "southwest", "midwest", "middle"])

Bird.create(scientific_name: "Strix varia", common_name: "Barred Owl", description: "Barred Owls roost quietly in forest trees during the day, though they can occasionally be heard calling in daylight hours. At night they hunt small animals, especially rodents, and give an instantly recognizable “Who cooks for you?” call.", size: "large", primary_color: "brown", secondary_color: "white", chest_color: "white", distinct_pattern: ["colored streaks"], habitat: "forest", nesting: "tree", call_description: "hoot", img: "https://mlsvc01-prod.s3.amazonaws.com/a01e1c02401/fa94e9b6-7fbe-439a-8481-e25d013451aa.jpg", region: ["northeast", "southeast", "northeast"])

Bird.create(scientific_name: "Mniotilta varia", common_name: "Black-and-White Warbler", description: "Black-and-white Warblers act more like nuthatches than warblers, foraging for hidden insects in the bark of trees by creeping up, down, and around branches and trunks. Despite their arboreal foraging habits, they nest on the ground at the bases of trees.", size: "medium", primary_color: "black", secondary_color: "white", chest_color: "black", distinct_pattern: ["wingbars", "colored streaks"], habitat: "forest", nesting: "ground", call_description: "song-like", img: "http://www.tringa.org/images/8974_Black-and-white_Warbler_04-15-2012_1.jpg", region: ["southeast", "northeast"])

Bird.create(scientific_name: "Setophaga striata", common_name: "Blackpoll Warbler", description: "Blackpoll Warblers pick insects off foliage, but they also tend to forage near the trunks of evergreen trees, especially on the breeding grounds. During spring migration, they sing while searching for food, often hiding among leaves and branches in deciduous trees and shrubs.", size: "medium", primary_color: "black", secondary_color: "white", chest_color: "white", distinct_pattern: ["colored cap", "colored streaks"], habitat: "forest", nesting: "tree", call_description: "squeak", img: "http://www.borealbirds.org/sites/default/files/styles/lightbox_max_wh/public/bird_images/blackpoll-warbler.jpg?itok=Ui9U06VO", region: ["southeast", "northeast", "middle", "midwest"])

Bird.create(scientific_name: "Setophaga caerulescens", common_name: "Black-throated Blue Warbler", description: "The lazy, buzzy song of the Black-throated Blue Warbler comes from the undergrowth of leafy eastern woods. Although the bird usually keeps to the shady understory, it is not especially shy; a birder who walks quietly on trails inside the forest may observe it closely. It moves about rather actively in its search for insects, but often will forage in the same immediate area for minutes at a time, rather than moving quickly through the forest like some warblers.", size: "small", primary_color: "blue", secondary_color: "black", chest_color: "white", distinct_pattern: ["colored streaks", "wingbars"], habitat: "forest", nesting: "shrub", call_description: "song-like", img: "http://www.lloydspitalnikphotos.com/d/11970-3/black-throated_blue_warbler_R2D0923.jpg", region: ["southeast", "northeast"])

Bird.create(scientific_name: "Setophaga virens", common_name: "Black-throated Green Warbler", description: "The lazy, buzzy song of the Black-throated Blue Warbler comes from the undergrowth of leafy eastern woods. Although the bird usually keeps to the shady understory, it is not especially shy; a birder who walks quietly on trails inside the forest may observe it closely. It moves about rather actively in its search for insects, but often will forage in the same immediate area for minutes at a time, rather than moving quickly through the forest like some warblers.", size: "small", primary_color: "yellow", secondary_color: "gray", chest_color: "white", distinct_pattern: ["colored streaks", "wingbars"], habitat: "forest", nesting: "shrub", call_description: "song-like", img: "http://www.tringa.org/images/8955_Black-throated_Green_Warbler_05-05-2012_3.jpg", region: ["middle", "midwest", "southeast", "northeast"])

Bird.create(scientific_name: "Polioptila caerulea", common_name: "Blue-Gray Gnatcatcher", description: "The energetic Blue-gray Gnatchatcher rarely slows down, fluttering after small insects among shrubs and trees with its tail cocked at a jaunty angle. Blue-gray Gnatcatchers often take food from spiderwebs and also abscond with strands of webbing for their tiny nests, which are shaped like tree knots.", size: "small", primary_color: "gray", secondary_color: "white", chest_color: "white", distinct_pattern: ["eyerings"], habitat: "forest", nesting: "tree", call_description: "squeak", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/gnat_kenphenicie.jpg", region: ["northeast", "southeast", "midwest", "southwest"])

Bird.create(scientific_name: "Cyanocitta cristata", common_name: "Blue Jay", description: "Blue Jays make a large variety of calls that carry long distances. Most calls produced while the jay is perched within a tree. Usually flies across open areas silently, especially during migration. Stuffs food items in throat pouch to cache elsewhere; when eating, holds a seed or nut in feet and pecks it open.", size: "large", primary_color: "blue", secondary_color: "white", chest_color: "white", distinct_pattern: ["wingbars"], habitat: "forest", nesting: "tree", call_description: "caw", img: "https://s-media-cache-ak0.pinimg.com/736x/ef/51/d9/ef51d9777bfff6a3e8e38a7c3bb90ff4.jpg", region: ["northeast", "southeast", "midwest", "middle"])

Bird.create(scientific_name: "Molothrus ater", common_name: "Brown-Headed Cowbird", description: "Brown-headed Cowbirds feed on the ground in mixed-species groups of blackbirds and starlings. Males gather on lawns to strut and display for mates. Females prowl woodlands and edges in search of nests. Brown-headed Cowbirds are noisy, making a multitude of clicks, whistles and chatter-like calls in addition to a flowing, gurgling song.", size: "small", primary_color: "black", secondary_color: "brown", chest_color: "black", distinct_pattern: ["iridescent"], habitat: "grassland", nesting: "tree", call_description: "squeak", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/brown_headed_cowbird_4.jpg", region: ["northeast", "northwest", "middle", "midwest", "southeast", "southwest"])

Bird.create(scientific_name: "Sitta pusilla", common_name: "Brown-Headed Nuthatch", description: "Nuthatches zigzag their way up and down tree trunks and branches high in the canopy, squeaking as they go. Although their calls aren’t very loud there’s usually more than one in a group calling at the same time, so they won't go unheard. They are social birds and often fly in shallow dips from tree to tree with one trailing behind the other.", size: "small", primary_color: "gray", secondary_color: "brown", chest_color: "white", distinct_pattern: ["colored cap"], habitat: "forest", nesting: "cavity", call_description: "squeak", img: "http://www.alanmurphyphotography.com/galleryimagesfromemail3/Brown-headed-Nuthatch-6.jpg", region: ["southeast"])

Bird.create(scientific_name: "Toxostoma rufum", common_name: "Brown Thrasher", description: "Brown Thrashers skulk in shrubby tangles or forage on the ground below dense cover. They’re most obvious when they sing their loud songs from shrubs and treetops. The song is a complex string of many musical phrases (many copied from other birds’ songs, with each phrase typically sung twice before moving on). They also make a distinctive, harsh tsuck note.", size: "large", primary_color: "brown", secondary_color: "white", chest_color: "white", distinct_pattern: ["wingbars"], habitat: "scrub", nesting: "shrub", call_description: "song-like", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/bthrasher_rockytopk9.jpg", region: ["southeast", "northeast", "midwest"])

Bird.create(scientific_name: "Poecile carolinensis", common_name: "Carolina Chickadee", description: "Inquisitive and acrobatic. Except in the breeding season, associates with other Carolina Chickadees and a variety of other small species in feeding flocks that roam within a fairly large area. Despite being a flocking species, they normally space themselves fairly widely while eating.", size: "small", primary_color: "white", secondary_color: "black", chest_color: "white", distinct_pattern: ["colored cap"], habitat: "forest", nesting: "cavity", call_description: "squeak", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/carolina_chickadee_1.jpg", region: ["southeast"])

Bird.create(scientific_name: "Thryothorus ludovicianus", common_name: "Carolina Wren", description: "The Carolina Wren creeps around vegetated areas and scoots up and down tree trunks in search of insects and fruit. It explores yards, garages, and woodpiles, sometimes nesting there. This wren often cocks its tail upward while foraging and holds it down when singing. Carolina Wrens defend their territories with constant singing; they aggressively scold and chase off intruders.", size: "small", primary_color: "brown", secondary_color: "white", chest_color: "white", distinct_pattern: ["eyebrow"], habitat: "woodland", nesting: "cavity", call_description: "song-like", img: "http://www.animalspot.net/wp-content/uploads/2016/01/Carolina-Wren-Photos.jpg", region: ["southeast", "northeast", "midwest"])

Bird.create(scientific_name: "Bombycilla cedrorum", common_name: "Cedar Waxwing", description: "Cedar Waxwings are social birds that you’re likely to see in flocks year-round. They sit in fruiting trees swallowing berries whole, or pluck them in mid-air with a brief fluttering hover. They also course over water for insects, flying like tubby, slightly clumsy swallows.", size: "medium", primary_color: "brown", secondary_color: "gray", chest_color: "brown", distinct_pattern: ["color patch"], habitat: "woodland", nesting: "tree", call_description: "squeak", img: "https://media1.britannica.com/eb-media/58/128858-004-AAAA6962.jpg", region: ["southeast", "northeast", "midwest", "northeast", "northwest", "middle"])

Bird.create(scientific_name: "Setophaga pensylvanica", common_name: "Chestnut-Sided Warbler", description: "A common bird of second growth and scrubby forests, the Chestnut-sided Warbler is distinctive in appearance. No other warbler combines a greenish-yellow cap, a white breast, and reddish streaks down the sides.", size: "small", primary_color: "white", secondary_color: "gray", chest_color: "brown", distinct_pattern: ["colored cap", "colored streaks"], habitat: "woodland", nesting: "shrub", call_description: "song-like", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/cswa_jimmcree.jpg", region: ["southeast", "northeast", "midwest", "middle"])

Bird.create(scientific_name: "Chaetura pelagica", common_name: "Chimney Swift", description: "Chimney Swifts fly rapidly with nearly constant wingbeats, and often twist from side to side and bank erratically. Their wingbeats are stiff, with very little flex at the wrists. They often give a high, chattering call while they fly.", size: "small", primary_color: "gray", secondary_color: "brown", chest_color: "gray", distinct_pattern: ["N/A"], habitat: "town", nesting: "building", call_description: "squeak", img: "http://4.bp.blogspot.com/-HTXk65Y44uA/UG2WSmhlimI/AAAAAAAADy8/LpRW0oQvwI0/s1600/Chimney+swift+Chaetura+pelagica.jpg", region: ["southeast", "northeast", "middle", "midwest"])

Bird.create(scientific_name: "Spizella passerina", common_name: "Chipping Sparrow", description: "Chipping Sparrows feed on the ground, take cover in shrubs, and sing from the tops of small trees (often evergreens). You’ll often see loose groups of them flitting up from open ground. When singing, they cling to high outer limbs. On the ground they hop or run through grasses searching for seeds.", size: "medium", primary_color: "brown", secondary_color: "white", chest_color: "white", distinct_pattern: ["wingbars", "eyebrow"], habitat: "woodland", nesting: "shrub", call_description: "squeak", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/chipping_sparrow_6.jpg", region: ["southeast", "northeast", "middle", "midwest", "southwest", "northwest"])

Bird.create(scientific_name: "Quiscalus quiscula", common_name: "Common Grackle", description: "You’ll often find Common Grackles in large flocks, flying or foraging on lawns and in agricultural fields. They strut on their long legs, pecking for food rather than scratching. At feeders Common Grackles dominate smaller birds. When resting they sit atop trees or on telephone lines, keeping up a raucous chattering. Flight is direct, with stiff wingbeats.", size: "large", primary_color: "black", secondary_color: "blue", chest_color: "black", distinct_pattern: ["iridescent"], habitat: "woodland", nesting: "tree", call_description: "caw", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/common_grackle_6.jpg", region: ["southeast", "northeast", "middle", "midwest"])

Bird.create(scientific_name: "Geothlypis trichas", common_name: "Common Yellowthroat", description: "Common Yellowthroats spend much of their time skulking low to the ground in dense thickets and fields, searching for small insects and spiders. Males sing a very distinctive, rolling wichety-wichety-wichety song, and both sexes give a full-sounding chuck note that is easy to learn. During migration, this is often the most common warbler found in fields and edges. It sometimes joins other warbler species in mixed foraging flocks.", size: "small", primary_color: "yellow", secondary_color: "black", chest_color: "yellow", distinct_pattern: ["colored mask"], habitat: "scrub", nesting: "shrub", call_description: "caw", img: "https://www.allaboutbirds.org/guide/PHOTO/LARGE/coye_joeldeyoung2.jpg", region: ["southeast", "northeast", "middle", "midwest", "northwest"])

Bird.create(scientific_name: "Junco hyemalis", common_name: "Dark-Eyed Junco", description: "Dark-eyed Juncos are birds of the ground. They hop around the bases of trees and shrubs in forests or venture out onto lawns looking for fallen seeds. You’ll often hear their high chip notes, given almost absent-mindedly while foraging, or intensifying as they take short, low flights through cover.", size: "medium", primary_color: "gray", secondary_color: "brown", chest_color: "gray", habitat: "forest", nesting: "ground", call_description: "song-like", img: "https://gocampbellriver.com/wp-content/uploads/2015/05/Darkeyed-Junco-Campbell-River-Vancouver-Island.jpg" , region: ["southeast", "northeast", "middle", "midwest", "northwest", "southwest"])

Bird.create(scientific_name: "Picoides pubescens", common_name: "Downy Woodpecker", description: "Downy Woodpeckers hitch around tree limbs and trunks or drop into tall weeds to feed on galls, moving more acrobatically than larger woodpeckers. Their rising-and-falling flight style is distinctive of many woodpeckers. In spring and summer, Downy Woodpeckers make lots of noise, both with their shrill whinnying call and by drumming on trees.", size: "small", primary_color: "black", secondary_color: "white", chest_color: "white", distinct_pattern: ["colored streaks"], habitat: "forest", nesting: "cavity", call_description: "squeak", img: "http://www.portaltodiscovery.org/carmans/carmansguide/birds/pix/downy-woodpecker.jpg" , region: ["southeast", "northeast", "middle", "midwest", "northwest", "southwest"])

Bird.create(scientific_name: "Sialia sialis", common_name: "Eastern Bluebird", description: "Eastern Bluebirds perch erect on wires, posts, and low branches in open country, scanning the ground for prey. They feed by dropping to the ground onto insects or, in fall and winter, by perching on fruiting trees to gulp down berries. Bluebirds commonly use nest boxes as well as old woodpecker holes.", size: "small", primary_color: "blue", secondary_color: "orange", chest_color: "orange", habitat: "forest", nesting: "cavity", call_description: "squeak", img: "http://www.dec.ny.gov/images/administration_images/wwbluebirdleft.jpg" , region: ["southeast", "northeast", "middle", "midwest"])

Bird.create(scientific_name: "Sayornis phoebe", common_name: "Eastern Phoebe", description: "The Eastern Phoebe generally perches low in trees or on fencelines. Phoebes are very active, making short flights to capture insects and very often returning to the same perch. They make sharp “peep” calls in addition to their familiar “phoebe” vocalizations. When perched, Eastern Phoebes wag their tails down and up frequently.", size: "medium", primary_color: "gray", secondary_color: "brown", chest_color: "white", distinct_pattern: ["colored streaks"], habitat: "woodland", nesting: "building", call_description: "squeak", img: "http://www.fairbanksmuseum.org/community/blog/wp-content/uploads/2015/04/Eastern-Phoebe-F2.jpg" , region: ["southeast", "northeast", "midwest"])

Bird.create(scientific_name: "Pipilo erythrophthalmus", common_name: "Eastern Towhee", description: "Eastern Towhees spend most of their time on the ground, scratching at leaves using both feet at the same time, in a kind of backwards hop. They spend lots of time concealed beneath thick underbrush. You may see this bird more often when it climbs into shrubs and low trees to sing.", size: "large", primary_color: "black", secondary_color: "orange", chest_color: "orange", distinct_pattern: ["colored streaks"], habitat: "scrub", nesting: "ground", call_description: "song-like", img: "https://www.carolinabirdclub.org/gallery/Austin/images/Eastern_Towhee_CANT2IJAN272013_227CUT.jpg" , region: ["southeast", "northeast", "midwest"])